<?php

namespace JardinBundle\Repository;

/**
 * JarenfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JarenfantRepository extends \Doctrine\ORM\EntityRepository
{
}
